# include <stdio.h>

/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const int MAX = 4000000;

int main(int argc, char const *argv[])
{
	int a = 1, b = 2, sum = 2;
	int c;
	while(1){
		c = a + b;
		if(c > MAX){
			break;
		}
		if(c % 2 == 0){
			sum += c;
			printf("%d\n", c);
		}
		a = b;
		b = c;
	}
	printf("%d\n",sum);
	return 0;
}





